### ISSUE TITLE
Clarity on PCA slides

### ISSUE THREAD

**Issue by jisungk** [SML201/lectures#1]
On lecture 12, slide titled "Procedure", the following text is included:

> **One this is found**, then a least squares linear regression of each xi on x˜ (with no intercept) is performed and the residuals are obtained. The next principal component (PC2) is then calculated using the same procedure.

It might be helpful if it is explained that in this "recursive" process of computing principal components, during every step, the previous principal component is removed from the data.

Also, it appears that the phrase "**One this is found**" contains a grammatical error.

**Comment by jdstorey** [comment]
Fixed the typo and mentioned it is iterative.
